---
- name: ensure mariadb is at the latest version
  yum:
    name: mariadb-server
    state: latest

- name: ensure mariadb is running
  service:
    name: mariadb
    state: started

- name: copy template sql
  template: src=createdb.sql dest=/opt/

- name: copy template sh
  template: src=createdb.sh dest=/opt/

- name: create database
  command: sh /opt/createdb.sh
