---

- name: Download mysql connector
  get_url: url=http://www.java2s.com/Code/JarDownload/mysql/mysql-connector-java-5.1.21.jar.zip dest=/opt/

- name: Extract archive
  command: chdir=/usr/share /bin/unzip /opt/ -C /opt/ creates=/opt/mysql-connector-java-5.1.21.jar

- name: Copy jar to lib
  command: cp /opt/mysql-connector-java-5.1.21.jar /opt/apache-tomcat-7.0.61/lib

- name: copy template sql
  template: src=createdb.sql dest=/opt/

- name: create database
  command: chdir=/opt mysql < createdb.sql